require('nvim-treesitter.configs').setup {
    ensure_installed = {
        'bash',
        'bibtex',
        'c',
        'c_sharp',
        'cmake',
        'comment',
        'cpp',
        'css',
        'csv',
        'dockerfile',
        'dot',
        'doxygen',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'glsl',
        'go',
        'gomod',
        'gosum',
        'gowork',
        'graphql',
        'haskell',
        'hlsl',
        'html',
        'ini',
        'java',
        'javascript',
        'json',
        'kotlin',
        'latex',
        'llvm',
        'lua',
        'markdown',
        'markdown_inline',
        'meson',
        'ninja',
        'objc',
        'ocaml',
        'ocaml_interface',
        'pascal',
        'passwd',
        'pem',
        'perl',
        'php',
        'promql',
        'python',
        'regex',
        'requirements',
        'rst',
        'ruby',
        'rust',
        'scala',
        'scss',
        'sql',
        'ssh_config',
        'toml',
        'tsx',
        'typescript',
        'verilog',
        'vim',
        'wgsl',
        'xml',
        'yaml',
    },

    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}

require('hl-mdcodeblock').setup {
}
